---
title: "traffic_fatalities_sf_2010_2018"
author: "Jeremie Young"
date: "November 6, 2018"
output: html_document
---

# load accident dataset as CSV file
```{r}
library(readr)
CollisionRecords2010_2018 -> read_csv("C:/Users/Jeremie/Google Drive/Springboard Intro to Data Science/Capstone/Raw Datasets/CollisionRecords2010_2018.txt")
head(CollisionRecords2010_2018)

```

# import both dplyr and tidyr packages to use
```{r}
library(dplyr)
library(tidyr)
```


# subset dataframe by removing unused variables
```{r}
CollisionRecords2010_2018 <- CollisionRecords2010_2018 %>% 
             select(-JURIS, -OFFICER_ID, -REPORTING_DISTRICT, -CHP_SHIFT, -CITY_DIVISION_LAPD, -CITY_DIVISION_LAPD, -CALTRANS_COUNTY, -CALTRANS_DISTRICT, -ROUTE_SUFFIX, -POSTMILE_PREFIX, -POSTMILE, -CHP_ROAD_TYPE)
head(CollisionRecords2010_2018)

```


# further subset by observations to include only incidents that involve and injuries or deaths
```{r}
CollisionRecords2010_2018 <- CollisionRecords2010_2018 %>% 
             filter(NUMBER_KILLED > 0 | NUMBER_INJURED > 0)
```


