---
title: "traffic_fatalities_sf"
author: "Jeremie Young"
date: "November 6, 2018"
output: html_document
---

# load accident dataset as CSV file
```{r}
library(readr)
CollisionRecords <- read_csv("C:/Users/Jeremie/Google Drive/Springboard Intro to Data Science/Capstone/Raw Datasets/CollisionRecords2010_2018.txt")
head(CollisionRecords)

```

# import both dplyr and tidyr packages to use
```{r}
library(dplyr)
library(tidyr)
```


# subset dataframe by removing unused variables
```{r}
CollisionRecords <- CollisionRecords %>% 
             select(-JURIS, -OFFICER_ID, -REPORTING_DISTRICT, -CHP_SHIFT, -CITY_DIVISION_LAPD, -CITY_DIVISION_LAPD, -CALTRANS_COUNTY, -CALTRANS_DISTRICT, -ROUTE_SUFFIX, -POSTMILE_PREFIX, -POSTMILE, -CHP_ROAD_TYPE)
head(CollisionRecords)

```

# begin geocoding coordinate extraction process - concatenate/unite cross streets
```{r}
CollisionRecords <- CollisionRecords %>% 
              unite(CROSS_ST, PRIMARY_RD, SECONDARY_RD, sep = " & ")
```

# create new column for city and state to insert into dataframe
```{r}
library(tibble)
CITY <- "SAN FRANCISCO"
STATE <- "CA"
CollisionRecords <- CollisionRecords %>% 
    add_column(CITY, STATE, .after = "CROSS_ST")
```

# subset CASE_ID, CROSS_ST, CITY, STATE as csv export to extract coordinates on https://www.geocod.io/
```{r}
coordinates <- CollisionRecords %>%  
    select(CASE_ID, CROSS_ST:STATE)
write.table(coordinates, "coordinates.csv", row.names = FALSE, sep = ",")

```



